name: Release null0x686F QoL

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Mod Folder
        run: |
          mkdir release_build
          zip -r release_build/null0x686F_QoL.zip Contents/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_build/null0x686F_QoL.zip
          generate_release_notes: true

      - name: Move floating 'latest' tag to this release
        run: |
          git tag -f latest
          git push origin latest --force

      - name: Update 'latest' release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: release_build/null0x686F_QoL.zip
          generate_release_notes: false
          prerelease: false
